extends:
  - semistandard
  - plugin:prettier/recommended
  - plugin:lodash-fp/recommended
plugins:
  - prettier
  - lodash-fp
rules:
  prettier/prettier:
    - error
    -
      singleQuote: true
      bracketSpacing: false
  strict:
    - error
    - safe
overrides:
  - files:
    - index.js
    parserOptions:
      sourceType: script
    rules:
      no-global-assign: off
  - files:
    - test/**/*.js
    env:
      mocha: true
