extends:
  - semistandard
  - plugin:lodash-fp/recommended
  - prettier
plugins:
  - prettier
  - lodash-fp
rules:
  prettier/prettier:
    - error
    -
      singleQuote: true
      bracketSpacing: false
  strict:
    - error
    - safe
