extends:
  - semistandard
  - plugin:lodash-fp/recommended
parserOptions:
  sourceType: script
plugins:
  - lodash-fp
rules:
  strict:
    - error
    - safe
  max-len:
    - error
    -
      code: 80
      ignoreComments: true
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
